### PR TITLE
Fix storybook webpack import

### PR DESCRIPTION
**Pull request by rohandang**
Fixes error:

```
Creating bundle... TypeError: defaultStorybookConfig is not a function
    at Object.customizeWebpackConfig (/Users/rohandang/dev/consumer/packages/storybook/node_modules/happo-plugin-storybook/index.js:30:62)
    at /Users/rohandang/dev/consumer/packages/storybook/node_modules/happo.io/build/createWebpackBundle.js:74:25
    at Array.forEach (<anonymous>)
    at /Users/rohandang/dev/consumer/packages/storybook/node_modules/happo.io/build/createWebpackBundle.js:72:13
    at Generator.next (<anonymous>)
    at step (/Users/rohandang/dev/consumer/packages/storybook/node_modules/happo.io/build/createWebpackBundle.js:23:191)
    at /Users/rohandang/dev/consumer/packages/storybook/node_modules/happo.io/build/createWebpackBundle.js:23:437
    at new Promise (<anonymous>)
    at /Users/rohandang/dev/consumer/packages/storybook/node_modules/happo.io/build/createWebpackBundle.js:23:99
    at createWebpackBundle (/Users/rohandang/dev/consumer/packages/storybook/node_modules/happo.io/build/createWebpackBundle.js:116:17)
```

### CODE REVIEW

**Comment by rohandang** [comment]
@trotzig I think we need this fix ^

**Comment by trotzig** [comment]
Thanks! I was expecting this to break at some time. Reaching in to a dependency like this isn't great (but I couldn't find a better way). 

What version of storybook are you on? I think we need to handle both cases (when the import is a function and an object). Something like 

```js
const confFunc = typeof storybookWebpack === 'function' ? storybookWebpack : storybookWebpack.createDefaultWebpackConfig;
```

**Comment by trotzig** [comment]
Scrap that comment about needing to support both versions. It looks like we always have the createDefaultWebpackConfig function available.

**Comment by trotzig** [comment]
Version 1.1.2 was just released, and it includes this fix. Thanks @rohandang!

**Pull request merged**
